version: "3"
services:
  luxorbit:
    build: .
    environment:
      - STRAVA_CLIENT_ID=1312
      - STRAVA_CLIENT_SECRET=verysecret
      - LUXORBIT_BASE_URL=http://localhost:4567
    ports:
      - 4567:4567

  worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A luxorbit.celery worker --loglevel=info
    environment:
      - STRAVA_CLIENT_ID=1312
      - STRAVA_CLIENT_SECRET=verysecret
      - LUXORBIT_BASE_URL=http://localhost:4567
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - 6379:6379
